[package]
name = "free_sb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
zip = "0.6.5"
quick-xml = "0.36.2"
calamine = "0.21"
