[package]
name = "free_sb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = '2.3' # 遍历
docx-rs = "0.4.17"
zip = "0.6"
xml-rs = "2.3.2"